version: '3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./var/mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www/html:/code
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./ops/php-fpm
    volumes:
      - ./www/html:/code
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql
      - redis
      - rabbitmq
      - elasticsearch

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./var/redis:/data

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./var/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      # BLACKFIRE_SERVER_ID: SERVER-ID
      # BLACKFIRE_SERVER_TOKEN: SERVER-TOKEN
